import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/reactive/index.ts",
    "src/storefront/index.ts",
    "src/cart/index.ts",
    "src/utils/index.ts",
    "src/cache-adapters/index.ts",
    "src/catalog/index.ts",
    "src/consent/index.ts",
    "src/customer/index.ts",
    "src/i18n/index.ts",
    "src/image/index.ts",
    "src/media/index.ts",
    "src/search/index.ts",
    "src/security/index.ts",
    "src/seo/index.ts",
    "src/server/index.ts",
    "src/shop-pay/index.ts",
    "src/rich-text/index.ts",
    "src/money/index.ts",
    "src/metafields/index.ts",
    "src/pagination/index.ts",
    "src/analytics/index.ts",
    "src/analytics-shopify/index.ts",
  ],
  format: ["esm"],
  dts: true,
  splitting: true,
  treeshake: true,
  clean: true,
  sourcemap: true,
  target: "es2022",
});
